### ISSUE TITLE
Problems to set-up

### ISSUE THREAD

**Issue by markusr** [vshn/icingaweb2-module-grafana#4]
I am trying to get this running with our installation. We are running Icinga Web 2.4.0. I successfully installed the plugin, but I have problems setting it up.
Here are my questions:

- Is there also support for Grafana running with https? And how do I set it in the ```config.ini```?
- Is it possible to add a default grafana dashboard? Or can I use this ["Official Icinga Dashboard"](https://grafana.net/dashboards/381) ?

**Comment by Mikesch-mp** [comment]
Hello,

you can configure Grafana-Server to use https, just read the docs at http://docs.grafana.org/installation/configuration/#protocol, then just go to Configuration->Modules->grafana->Configuration Tab and change the protocol used by the module to https in the Icingaweb2 interface.

You can use whatever dashboard you want, the 2 i provide are the only i will support :) The module just need a dashboard named "icinga2-default" for services that are not configured to use a given dashboard.

Regards,
Carsten

**Comment by marcofl** [comment]
- yes, https is the default: https://github.com/vshn/icingaweb2-module-grafana/blob/master/library/Grafana/Grapher.php#L24
- we have our own dashboard, but it's quite independent of the dashboard you use. just set correct dashboard and panel it. see README.

**Comment by markusr** [comment]
I switched to another [project](https://github.com/Mikesch-mp/icingaweb2-module-grafana) which has the same name and is on [exchange.icinga.com](https://exchange.icinga.com/cark/Grafana+Module).
