### ISSUE TITLE
merge the 2 module-grafana projects

### ISSUE THREAD

**Issue by marcofl** [vshn/icingaweb2-module-grafana#6]
We should try to merge this project with https://github.com/Mikesch-mp/icingaweb2-module-grafana, let's discuss this in https://github.com/Mikesch-mp/icingaweb2-module-grafana/issues/10

**Comment by Mikesch-mp** [comment]
Wäre super wenn sich mal jemand melden würde.

**Comment by Mikesch-mp** [comment]
Nachdem sich niemand meldet, wird hier erstmal nix gemerged.

**Comment by marcofl** [comment]
Hi @Mikesch-mp,
Sorry I somehow forgot about this for a while. As it looks, the community is more into you module. So I'm not sure if it's worth the effort to even try merging. @davidgubler wrote our module. He's currently on vacation, I'll discuss this with him when he's back. My plan is to test, if your module is a replacements for our version, add missing features if there are any and then trash our module.

**Comment by marcofl** [comment]
Hi @Mikesch-mp,
We analysed you module and decided to try migrate to it. When done, we don't think there is anything to merge in your module.

**Comment by davidgubler** [comment]
Hi @Mikesch-mp,

I've migrated our setup to your module today and things seem to work fine. I'm therefore closing this.
